// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Matter      *matter
	RecycleBin  *recycleBin
	Storage     *storage
	UserStorage *userStorage
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Matter = &Q.Matter
	RecycleBin = &Q.RecycleBin
	Storage = &Q.Storage
	UserStorage = &Q.UserStorage
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Matter:      newMatter(db, opts...),
		RecycleBin:  newRecycleBin(db, opts...),
		Storage:     newStorage(db, opts...),
		UserStorage: newUserStorage(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Matter      matter
	RecycleBin  recycleBin
	Storage     storage
	UserStorage userStorage
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Matter:      q.Matter.clone(db),
		RecycleBin:  q.RecycleBin.clone(db),
		Storage:     q.Storage.clone(db),
		UserStorage: q.UserStorage.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Matter:      q.Matter.replaceDB(db),
		RecycleBin:  q.RecycleBin.replaceDB(db),
		Storage:     q.Storage.replaceDB(db),
		UserStorage: q.UserStorage.replaceDB(db),
	}
}

type queryCtx struct {
	Matter      IMatterDo
	RecycleBin  IRecycleBinDo
	Storage     IStorageDo
	UserStorage IUserStorageDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Matter:      q.Matter.WithContext(ctx),
		RecycleBin:  q.RecycleBin.WithContext(ctx),
		Storage:     q.Storage.WithContext(ctx),
		UserStorage: q.UserStorage.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
