dist: ./build/release
before:
  hooks:
    - go mod download
builds:
  - id: server
    main: ./main.go
    binary: bin/{{ .ProjectName }}
    ldflags:
      - -s -w
      - -X github.com/saltbo/{{ .ProjectName }}/cmd.release={{.Version}}
      - -X github.com/saltbo/{{ .ProjectName }}/cmd.commit={{.Commit}}
      - -X github.com/saltbo/{{ .ProjectName }}/cmd.repo={{.GitURL}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

release:
  prerelease: auto
  footer: |
    ## Docker Images
    
    - `saltbo/{{ .ProjectName }}:{{ .Version }}`
    

dockers:
  - image_templates:
      - "saltbo/{{ .ProjectName }}:{{ .Version }}"
#      - "saltbo/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
#      - "saltbo/{{ .ProjectName }}:latest"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    format_overrides: # archive as zip on Windows
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - deployments/*
      - install.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - file_name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/saltbo/{{ .ProjectName }}
    description: A self-hosted cloud disk base on the cloud storage
    maintainer: Ambor <saltbo@foxmail.com>
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - golang