UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.engine') WHERE json_type(`runtime`, '$.engine') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.state') WHERE json_type(`runtime`, '$.state') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.phase') WHERE json_type(`runtime`, '$.phase') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.message') WHERE json_type(`runtime`, '$.message') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.updatedAt') WHERE json_type(`runtime`, '$.updatedAt') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.connections') WHERE json_type(`runtime`, '$.connections') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.trackers') WHERE json_type(`runtime`, '$.trackers') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.peers') WHERE json_type(`runtime`, '$.peers') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.files') WHERE json_type(`runtime`, '$.files') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.torrent.infoHash') WHERE json_type(`runtime`, '$.torrent.infoHash') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.torrent.name') WHERE json_type(`runtime`, '$.torrent.name') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.torrent.seeders') WHERE json_type(`runtime`, '$.torrent.seeders') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.torrent.leechers') WHERE json_type(`runtime`, '$.torrent.leechers') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.torrent.peers') WHERE json_type(`runtime`, '$.torrent.peers') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.seeding.enabled') WHERE json_type(`runtime`, '$.seeding.enabled') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.seeding.active') WHERE json_type(`runtime`, '$.seeding.active') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.seeding.uploadedBytes') WHERE json_type(`runtime`, '$.seeding.uploadedBytes') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.seeding.uploadBytesPerSecond') WHERE json_type(`runtime`, '$.seeding.uploadBytesPerSecond') = 'null';--> statement-breakpoint
UPDATE `download_tasks` SET `runtime` = json_remove(`runtime`, '$.seeding.ratio') WHERE json_type(`runtime`, '$.seeding.ratio') = 'null';
