name = "zpan"
compatibility_date = "2024-12-01"
pages_build_output_dir = "../../dist"

[vars]
BETTER_AUTH_SECRET = "zpan-test-secret"

[[d1_databases]]
binding = "DB"
database_name = "zpan-db"
database_id = "local"
