/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as STokenRouteImport } from './routes/s/$token'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSharesIndexRouteImport } from './routes/_authenticated/shares/index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedStoragesIndexRouteImport } from './routes/_authenticated/storages/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRecycleBinIndexRouteImport } from './routes/_authenticated/recycle-bin/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedTeamsInviteRouteImport } from './routes/_authenticated/teams/invite'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedTeamsTeamIdRouteRouteImport } from './routes/_authenticated/teams/$teamId/route'
import { Route as AuthenticatedTeamsTeamIdIndexRouteImport } from './routes/_authenticated/teams/$teamId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminStoragesIndexRouteImport } from './routes/_authenticated/admin/storages/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedTeamsTeamIdSettingsRouteImport } from './routes/_authenticated/teams/$teamId/settings'
import { Route as AuthenticatedTeamsTeamIdMembersRouteImport } from './routes/_authenticated/teams/$teamId/members'
import { Route as AuthenticatedTeamsTeamIdActivityRouteImport } from './routes/_authenticated/teams/$teamId/activity'
import { Route as AuthenticatedAdminSettingsAuthRouteImport } from './routes/_authenticated/admin/settings/auth'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharesIndexRoute =
  AuthenticatedSharesIndexRouteImport.update({
    id: '/shares/',
    path: '/shares/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoragesIndexRoute =
  AuthenticatedStoragesIndexRouteImport.update({
    id: '/storages/',
    path: '/storages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRecycleBinIndexRoute =
  AuthenticatedRecycleBinIndexRouteImport.update({
    id: '/recycle-bin/',
    path: '/recycle-bin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsInviteRoute =
  AuthenticatedTeamsInviteRouteImport.update({
    id: '/teams/invite',
    path: '/teams/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdRouteRoute =
  AuthenticatedTeamsTeamIdRouteRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdIndexRoute =
  AuthenticatedTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoragesIndexRoute =
  AuthenticatedAdminStoragesIndexRouteImport.update({
    id: '/storages/',
    path: '/storages/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdSettingsRoute =
  AuthenticatedTeamsTeamIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdMembersRoute =
  AuthenticatedTeamsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdActivityRoute =
  AuthenticatedTeamsTeamIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedTeamsTeamIdRouteRoute,
  } as any)
const AuthenticatedAdminSettingsAuthRoute =
  AuthenticatedAdminSettingsAuthRouteImport.update({
    id: '/settings/auth',
    path: '/settings/auth',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$token': typeof STokenRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/teams/invite': typeof AuthenticatedTeamsInviteRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/recycle-bin/': typeof AuthenticatedRecycleBinIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/storages/': typeof AuthenticatedStoragesIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/shares/': typeof AuthenticatedSharesIndexRoute
  '/admin/settings/auth': typeof AuthenticatedAdminSettingsAuthRoute
  '/teams/$teamId/activity': typeof AuthenticatedTeamsTeamIdActivityRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId/settings': typeof AuthenticatedTeamsTeamIdSettingsRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/storages/': typeof AuthenticatedAdminStoragesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$token': typeof STokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/teams/invite': typeof AuthenticatedTeamsInviteRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/recycle-bin': typeof AuthenticatedRecycleBinIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/storages': typeof AuthenticatedStoragesIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/shares': typeof AuthenticatedSharesIndexRoute
  '/admin/settings/auth': typeof AuthenticatedAdminSettingsAuthRoute
  '/teams/$teamId/activity': typeof AuthenticatedTeamsTeamIdActivityRoute
  '/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/teams/$teamId/settings': typeof AuthenticatedTeamsTeamIdSettingsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/storages': typeof AuthenticatedAdminStoragesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/u/$username': typeof UUsernameRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/teams/invite': typeof AuthenticatedTeamsInviteRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/recycle-bin/': typeof AuthenticatedRecycleBinIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/storages/': typeof AuthenticatedStoragesIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/shares/': typeof AuthenticatedSharesIndexRoute
  '/_authenticated/admin/settings/auth': typeof AuthenticatedAdminSettingsAuthRoute
  '/_authenticated/teams/$teamId/activity': typeof AuthenticatedTeamsTeamIdActivityRoute
  '/_authenticated/teams/$teamId/members': typeof AuthenticatedTeamsTeamIdMembersRoute
  '/_authenticated/teams/$teamId/settings': typeof AuthenticatedTeamsTeamIdSettingsRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/storages/': typeof AuthenticatedAdminStoragesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/teams/$teamId/': typeof AuthenticatedTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/u/$username'
    | '/s/$token'
    | '/teams/$teamId'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/teams/invite'
    | '/files/'
    | '/recycle-bin/'
    | '/settings/'
    | '/storages/'
    | '/teams/'
    | '/users/'
    | '/shares/'
    | '/admin/settings/auth'
    | '/teams/$teamId/activity'
    | '/teams/$teamId/members'
    | '/teams/$teamId/settings'
    | '/admin/settings/'
    | '/admin/storages/'
    | '/admin/users/'
    | '/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/u/$username'
    | '/s/$token'
    | '/'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/teams/invite'
    | '/files'
    | '/recycle-bin'
    | '/settings'
    | '/storages'
    | '/teams'
    | '/users'
    | '/shares'
    | '/admin/settings/auth'
    | '/teams/$teamId/activity'
    | '/teams/$teamId/members'
    | '/teams/$teamId/settings'
    | '/admin/settings'
    | '/admin/storages'
    | '/admin/users'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/u/$username'
    | '/s/$token'
    | '/_authenticated/'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/password'
    | '/_authenticated/settings/profile'
    | '/_authenticated/teams/invite'
    | '/_authenticated/files/'
    | '/_authenticated/recycle-bin/'
    | '/_authenticated/settings/'
    | '/_authenticated/storages/'
    | '/_authenticated/teams/'
    | '/_authenticated/users/'
    | '/_authenticated/shares/'
    | '/_authenticated/admin/settings/auth'
    | '/_authenticated/teams/$teamId/activity'
    | '/_authenticated/teams/$teamId/members'
    | '/_authenticated/teams/$teamId/settings'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/storages/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  UUsernameRoute: typeof UUsernameRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shares/': {
      id: '/_authenticated/shares/'
      path: '/shares'
      fullPath: '/shares/'
      preLoaderRoute: typeof AuthenticatedSharesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storages/': {
      id: '/_authenticated/storages/'
      path: '/storages'
      fullPath: '/storages/'
      preLoaderRoute: typeof AuthenticatedStoragesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/recycle-bin/': {
      id: '/_authenticated/recycle-bin/'
      path: '/recycle-bin'
      fullPath: '/recycle-bin/'
      preLoaderRoute: typeof AuthenticatedRecycleBinIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/invite': {
      id: '/_authenticated/teams/invite'
      path: '/teams/invite'
      fullPath: '/teams/invite'
      preLoaderRoute: typeof AuthenticatedTeamsInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId/': {
      id: '/_authenticated/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/storages/': {
      id: '/_authenticated/admin/storages/'
      path: '/storages'
      fullPath: '/admin/storages/'
      preLoaderRoute: typeof AuthenticatedAdminStoragesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/teams/$teamId/settings': {
      id: '/_authenticated/teams/$teamId/settings'
      path: '/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdSettingsRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/members': {
      id: '/_authenticated/teams/$teamId/members'
      path: '/members'
      fullPath: '/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/teams/$teamId/activity': {
      id: '/_authenticated/teams/$teamId/activity'
      path: '/activity'
      fullPath: '/teams/$teamId/activity'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdActivityRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRouteRoute
    }
    '/_authenticated/admin/settings/auth': {
      id: '/_authenticated/admin/settings/auth'
      path: '/settings/auth'
      fullPath: '/admin/settings/auth'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAuthRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSettingsAuthRoute: typeof AuthenticatedAdminSettingsAuthRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminStoragesIndexRoute: typeof AuthenticatedAdminStoragesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSettingsAuthRoute: AuthenticatedAdminSettingsAuthRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminStoragesIndexRoute: AuthenticatedAdminStoragesIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdRouteRouteChildren {
  AuthenticatedTeamsTeamIdActivityRoute: typeof AuthenticatedTeamsTeamIdActivityRoute
  AuthenticatedTeamsTeamIdMembersRoute: typeof AuthenticatedTeamsTeamIdMembersRoute
  AuthenticatedTeamsTeamIdSettingsRoute: typeof AuthenticatedTeamsTeamIdSettingsRoute
  AuthenticatedTeamsTeamIdIndexRoute: typeof AuthenticatedTeamsTeamIdIndexRoute
}

const AuthenticatedTeamsTeamIdRouteRouteChildren: AuthenticatedTeamsTeamIdRouteRouteChildren =
  {
    AuthenticatedTeamsTeamIdActivityRoute:
      AuthenticatedTeamsTeamIdActivityRoute,
    AuthenticatedTeamsTeamIdMembersRoute: AuthenticatedTeamsTeamIdMembersRoute,
    AuthenticatedTeamsTeamIdSettingsRoute:
      AuthenticatedTeamsTeamIdSettingsRoute,
    AuthenticatedTeamsTeamIdIndexRoute: AuthenticatedTeamsTeamIdIndexRoute,
  }

const AuthenticatedTeamsTeamIdRouteRouteWithChildren =
  AuthenticatedTeamsTeamIdRouteRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTeamsTeamIdRouteRoute: typeof AuthenticatedTeamsTeamIdRouteRouteWithChildren
  AuthenticatedTeamsInviteRoute: typeof AuthenticatedTeamsInviteRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedRecycleBinIndexRoute: typeof AuthenticatedRecycleBinIndexRoute
  AuthenticatedStoragesIndexRoute: typeof AuthenticatedStoragesIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedSharesIndexRoute: typeof AuthenticatedSharesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTeamsTeamIdRouteRoute:
    AuthenticatedTeamsTeamIdRouteRouteWithChildren,
  AuthenticatedTeamsInviteRoute: AuthenticatedTeamsInviteRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedRecycleBinIndexRoute: AuthenticatedRecycleBinIndexRoute,
  AuthenticatedStoragesIndexRoute: AuthenticatedStoragesIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedSharesIndexRoute: AuthenticatedSharesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  UUsernameRoute: UUsernameRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
